name: Matrix Configuration

on: 
    push:
    workflow_dispatch:

jobs:
    deploy:
        strategy:
          matrix:
            os: [ubuntu-latest, ubuntu-20.04, window-latest]
            images: [hello-world, alpine]
        runs-on: ${{ matrix.os }}
        steps:
          - name: Echo docker details
            run: docker info

          - name: Run image on ${{ matrix.images }}
            run: docker run ${{ matrix.images }}

        
