name: Matrix Configuration

on: 
    push:
    workflow_dispatch:

jobs:
    deploy:
        strategy:
          fail-fast: false
          max-parallel: 2
          matrix:
            os: [ubuntu-latest, ubuntu-20.04, windows-latest]
            images: [hello-world, alpine]
            exclude:
              - os: windows-latest
            include:
              - images: amd64/alpine
                os: ubuntu-20.04
        runs-on: ${{ matrix.os }}
        steps:
          - name: Echo docker details
            if: matrix.os != 'windows-latest'
            run: docker info

          - name: Run image on ${{ matrix.images }}
            if: matrix.os != 'windows-latest'
            run: docker run ${{ matrix.images }}

        
