name: Matrix Configuration

on: 
    push:
    workflow_dispatch:

jobs:
    deploy_on_ubuntu:
        runs-on: ubuntu-latest
        steps:
          - name: Echo docker details
            run: docker info

          - name: Run image
            run: docker run hello-world

    deploy_on_window:
        runs-on: windows-latest
        steps:
          - name: Echo docker details
            run: docker info

          - name: Run image
            run: docker run hello-world
        
