name: Multi Jobs Workflow

on: push

jobs:
    build_jobs:
        runs-on: ubuntu-latest
        steps:
        # - name: Checkout code
        #   uses: actions/checkout@v3

        - name: Install Cowsay program
          run: sudo apt-get install cowsay -y
        
        - name: Execute Cowsay CMD
          run: cowsay -f dragon "Run for cover, I'm a DRAGON...RAWR" >> dragon.txt

        - name: Upload Dragon file
          uses: actions/upload-artifact@v4
          with:
            name: dragon-file
            path: dragon.txt

    test_jobs:
        needs: build_jobs
        runs-on: ubuntu-latest
        steps:
          - name: Download Dragon file
            uses: actions/download-artifact@v4
            with:
              name: dragon-file

          - name: Test file exists
            run: grep -i "dragon" dragon.txt

    deploy_jobs:
        needs: test_jobs
        runs-on: ubuntu-latest
        steps:
          - name: Download Dragon file
            uses: actions/download-artifact@v4
            with:
              name: dragon-file

          - name: Read file
            run: cat dragon.txt
          
          - name: Deploy
            run: echo Deploying on test env...
